/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as errors503RouteImport } from './routes/(errors)/503'
import { Route as errors500RouteImport } from './routes/(errors)/500'
import { Route as errors404RouteImport } from './routes/(errors)/404'
import { Route as errors403RouteImport } from './routes/(errors)/403'
import { Route as errors401RouteImport } from './routes/(errors)/401'
import { Route as authSignUpRouteImport } from './routes/(auth)/sign-up'
import { Route as authSignIn2RouteImport } from './routes/(auth)/sign-in-2'
import { Route as authSignInRouteImport } from './routes/(auth)/sign-in'
import { Route as authOtpRouteImport } from './routes/(auth)/otp'
import { Route as authForgotPasswordRouteImport } from './routes/(auth)/forgot-password'
import { Route as AuthenticatedSettingsRouteRouteImport } from './routes/_authenticated/settings/route'
import { Route as AuthenticatedUsersIndexRouteImport } from './routes/_authenticated/users/index'
import { Route as AuthenticatedTasksIndexRouteImport } from './routes/_authenticated/tasks/index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings/index'
import { Route as AuthenticatedOnboardingsIndexRouteImport } from './routes/_authenticated/onboardings/index'
import { Route as AuthenticatedOffersIndexRouteImport } from './routes/_authenticated/offers/index'
import { Route as AuthenticatedModelsIndexRouteImport } from './routes/_authenticated/models/index'
import { Route as AuthenticatedLeasingCompaniesIndexRouteImport } from './routes/_authenticated/leasing-companies/index'
import { Route as AuthenticatedHelpCenterIndexRouteImport } from './routes/_authenticated/help-center/index'
import { Route as AuthenticatedGenerationsIndexRouteImport } from './routes/_authenticated/generations/index'
import { Route as AuthenticatedEquipmentItemsIndexRouteImport } from './routes/_authenticated/equipment-items/index'
import { Route as AuthenticatedEnginesIndexRouteImport } from './routes/_authenticated/engines/index'
import { Route as AuthenticatedDocumentTemplatesIndexRouteImport } from './routes/_authenticated/document-templates/index'
import { Route as AuthenticatedDiscountsIndexRouteImport } from './routes/_authenticated/discounts/index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers/index'
import { Route as AuthenticatedColorsIndexRouteImport } from './routes/_authenticated/colors/index'
import { Route as AuthenticatedChatsIndexRouteImport } from './routes/_authenticated/chats/index'
import { Route as AuthenticatedCarRequestsIndexRouteImport } from './routes/_authenticated/car-requests/index'
import { Route as AuthenticatedBrandsIndexRouteImport } from './routes/_authenticated/brands/index'
import { Route as AuthenticatedAppsIndexRouteImport } from './routes/_authenticated/apps/index'
import { Route as AuthenticatedUsersAddRouteImport } from './routes/_authenticated/users/add'
import { Route as AuthenticatedSettingsNotificationsRouteImport } from './routes/_authenticated/settings/notifications'
import { Route as AuthenticatedSettingsDisplayRouteImport } from './routes/_authenticated/settings/display'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings/appearance'
import { Route as AuthenticatedSettingsAccountRouteImport } from './routes/_authenticated/settings/account'
import { Route as AuthenticatedModelsNewRouteImport } from './routes/_authenticated/models/new'
import { Route as AuthenticatedLeasingCompaniesNewRouteImport } from './routes/_authenticated/leasing-companies/new'
import { Route as AuthenticatedGenerationsNewRouteImport } from './routes/_authenticated/generations/new'
import { Route as AuthenticatedErrorsErrorRouteImport } from './routes/_authenticated/errors/$error'
import { Route as AuthenticatedEquipmentItemsNewRouteImport } from './routes/_authenticated/equipment-items/new'
import { Route as AuthenticatedEnginesNewRouteImport } from './routes/_authenticated/engines/new'
import { Route as AuthenticatedDocumentTemplatesNewRouteImport } from './routes/_authenticated/document-templates/new'
import { Route as AuthenticatedColorsNewRouteImport } from './routes/_authenticated/colors/new'
import { Route as AuthenticatedCarRequestsNewRouteImport } from './routes/_authenticated/car-requests/new'
import { Route as AuthenticatedBrandsNewRouteImport } from './routes/_authenticated/brands/new'
import { Route as AuthenticatedUsersUserIdIndexRouteImport } from './routes/_authenticated/users/$userId/index'
import { Route as AuthenticatedOnboardingsOnboardingIdIndexRouteImport } from './routes/_authenticated/onboardings/$onboardingId/index'
import { Route as AuthenticatedOffersNewIndexRouteImport } from './routes/_authenticated/offers/new/index'
import { Route as AuthenticatedGenerationsGenerationIdIndexRouteImport } from './routes/_authenticated/generations/$generationId/index'
import { Route as AuthenticatedCustomersCustomerIdIndexRouteImport } from './routes/_authenticated/customers/$customerId/index'
import { Route as AuthenticatedCarRequestsCarRequestIdIndexRouteImport } from './routes/_authenticated/car-requests/$carRequestId/index'
import { Route as AuthenticatedUsersUserIdEditRouteImport } from './routes/_authenticated/users/$userId/edit'
import { Route as AuthenticatedOffersNewOperationalLeasingRouteImport } from './routes/_authenticated/offers/new/operational-leasing'
import { Route as AuthenticatedOffersNewIndividualRouteImport } from './routes/_authenticated/offers/new/individual'
import { Route as AuthenticatedOffersNewDirectPurchaseRouteImport } from './routes/_authenticated/offers/new/direct-purchase'
import { Route as AuthenticatedOffersOfferIdEditRouteImport } from './routes/_authenticated/offers/$offerId.edit'
import { Route as AuthenticatedModelsModelIdEditRouteImport } from './routes/_authenticated/models/$modelId/edit'
import { Route as AuthenticatedLeasingCompaniesCompanyIdEditRouteImport } from './routes/_authenticated/leasing-companies/$companyId.edit'
import { Route as AuthenticatedGenerationsGenerationIdEquipmentRouteImport } from './routes/_authenticated/generations/$generationId/equipment'
import { Route as AuthenticatedGenerationsGenerationIdEditRouteImport } from './routes/_authenticated/generations/$generationId/edit'
import { Route as AuthenticatedEquipmentItemsItemIdEditRouteImport } from './routes/_authenticated/equipment-items/$itemId/edit'
import { Route as AuthenticatedEnginesEngineIdEditRouteImport } from './routes/_authenticated/engines/$engineId/edit'
import { Route as AuthenticatedDocumentTemplatesTemplateIdEditRouteImport } from './routes/_authenticated/document-templates/$templateId.edit'
import { Route as AuthenticatedColorsColorIdEditRouteImport } from './routes/_authenticated/colors/$colorId/edit'
import { Route as AuthenticatedCarRequestsCarRequestIdEditRouteImport } from './routes/_authenticated/car-requests/$carRequestId/edit'
import { Route as AuthenticatedBrandsBrandIdEditRouteImport } from './routes/_authenticated/brands/$brandId/edit'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const errors503Route = errors503RouteImport.update({
  id: '/(errors)/503',
  path: '/503',
  getParentRoute: () => rootRouteImport,
} as any)
const errors500Route = errors500RouteImport.update({
  id: '/(errors)/500',
  path: '/500',
  getParentRoute: () => rootRouteImport,
} as any)
const errors404Route = errors404RouteImport.update({
  id: '/(errors)/404',
  path: '/404',
  getParentRoute: () => rootRouteImport,
} as any)
const errors403Route = errors403RouteImport.update({
  id: '/(errors)/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const errors401Route = errors401RouteImport.update({
  id: '/(errors)/401',
  path: '/401',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignUpRoute = authSignUpRouteImport.update({
  id: '/(auth)/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignIn2Route = authSignIn2RouteImport.update({
  id: '/(auth)/sign-in-2',
  path: '/sign-in-2',
  getParentRoute: () => rootRouteImport,
} as any)
const authSignInRoute = authSignInRouteImport.update({
  id: '/(auth)/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const authOtpRoute = authOtpRouteImport.update({
  id: '/(auth)/otp',
  path: '/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const authForgotPasswordRoute = authForgotPasswordRouteImport.update({
  id: '/(auth)/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRouteRoute =
  AuthenticatedSettingsRouteRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersIndexRoute = AuthenticatedUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTasksIndexRoute = AuthenticatedTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedOnboardingsIndexRoute =
  AuthenticatedOnboardingsIndexRouteImport.update({
    id: '/onboardings/',
    path: '/onboardings/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersIndexRoute =
  AuthenticatedOffersIndexRouteImport.update({
    id: '/offers/',
    path: '/offers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsIndexRoute =
  AuthenticatedModelsIndexRouteImport.update({
    id: '/models/',
    path: '/models/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeasingCompaniesIndexRoute =
  AuthenticatedLeasingCompaniesIndexRouteImport.update({
    id: '/leasing-companies/',
    path: '/leasing-companies/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedHelpCenterIndexRoute =
  AuthenticatedHelpCenterIndexRouteImport.update({
    id: '/help-center/',
    path: '/help-center/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerationsIndexRoute =
  AuthenticatedGenerationsIndexRouteImport.update({
    id: '/generations/',
    path: '/generations/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentItemsIndexRoute =
  AuthenticatedEquipmentItemsIndexRouteImport.update({
    id: '/equipment-items/',
    path: '/equipment-items/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnginesIndexRoute =
  AuthenticatedEnginesIndexRouteImport.update({
    id: '/engines/',
    path: '/engines/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentTemplatesIndexRoute =
  AuthenticatedDocumentTemplatesIndexRouteImport.update({
    id: '/document-templates/',
    path: '/document-templates/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDiscountsIndexRoute =
  AuthenticatedDiscountsIndexRouteImport.update({
    id: '/discounts/',
    path: '/discounts/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColorsIndexRoute =
  AuthenticatedColorsIndexRouteImport.update({
    id: '/colors/',
    path: '/colors/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatsIndexRoute = AuthenticatedChatsIndexRouteImport.update({
  id: '/chats/',
  path: '/chats/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarRequestsIndexRoute =
  AuthenticatedCarRequestsIndexRouteImport.update({
    id: '/car-requests/',
    path: '/car-requests/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsIndexRoute =
  AuthenticatedBrandsIndexRouteImport.update({
    id: '/brands/',
    path: '/brands/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAppsIndexRoute = AuthenticatedAppsIndexRouteImport.update({
  id: '/apps/',
  path: '/apps/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersAddRoute = AuthenticatedUsersAddRouteImport.update({
  id: '/users/add',
  path: '/users/add',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsNotificationsRoute =
  AuthenticatedSettingsNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsDisplayRoute =
  AuthenticatedSettingsDisplayRouteImport.update({
    id: '/display',
    path: '/display',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/appearance',
    path: '/appearance',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedSettingsAccountRoute =
  AuthenticatedSettingsAccountRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => AuthenticatedSettingsRouteRoute,
  } as any)
const AuthenticatedModelsNewRoute = AuthenticatedModelsNewRouteImport.update({
  id: '/models/new',
  path: '/models/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLeasingCompaniesNewRoute =
  AuthenticatedLeasingCompaniesNewRouteImport.update({
    id: '/leasing-companies/new',
    path: '/leasing-companies/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerationsNewRoute =
  AuthenticatedGenerationsNewRouteImport.update({
    id: '/generations/new',
    path: '/generations/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedErrorsErrorRoute =
  AuthenticatedErrorsErrorRouteImport.update({
    id: '/errors/$error',
    path: '/errors/$error',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentItemsNewRoute =
  AuthenticatedEquipmentItemsNewRouteImport.update({
    id: '/equipment-items/new',
    path: '/equipment-items/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnginesNewRoute = AuthenticatedEnginesNewRouteImport.update({
  id: '/engines/new',
  path: '/engines/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentTemplatesNewRoute =
  AuthenticatedDocumentTemplatesNewRouteImport.update({
    id: '/document-templates/new',
    path: '/document-templates/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColorsNewRoute = AuthenticatedColorsNewRouteImport.update({
  id: '/colors/new',
  path: '/colors/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarRequestsNewRoute =
  AuthenticatedCarRequestsNewRouteImport.update({
    id: '/car-requests/new',
    path: '/car-requests/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsNewRoute = AuthenticatedBrandsNewRouteImport.update({
  id: '/brands/new',
  path: '/brands/new',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedUsersUserIdIndexRoute =
  AuthenticatedUsersUserIdIndexRouteImport.update({
    id: '/users/$userId/',
    path: '/users/$userId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingsOnboardingIdIndexRoute =
  AuthenticatedOnboardingsOnboardingIdIndexRouteImport.update({
    id: '/onboardings/$onboardingId/',
    path: '/onboardings/$onboardingId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersNewIndexRoute =
  AuthenticatedOffersNewIndexRouteImport.update({
    id: '/offers/new/',
    path: '/offers/new/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerationsGenerationIdIndexRoute =
  AuthenticatedGenerationsGenerationIdIndexRouteImport.update({
    id: '/generations/$generationId/',
    path: '/generations/$generationId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCustomersCustomerIdIndexRoute =
  AuthenticatedCustomersCustomerIdIndexRouteImport.update({
    id: '/customers/$customerId/',
    path: '/customers/$customerId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarRequestsCarRequestIdIndexRoute =
  AuthenticatedCarRequestsCarRequestIdIndexRouteImport.update({
    id: '/car-requests/$carRequestId/',
    path: '/car-requests/$carRequestId/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedUsersUserIdEditRoute =
  AuthenticatedUsersUserIdEditRouteImport.update({
    id: '/users/$userId/edit',
    path: '/users/$userId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersNewOperationalLeasingRoute =
  AuthenticatedOffersNewOperationalLeasingRouteImport.update({
    id: '/offers/new/operational-leasing',
    path: '/offers/new/operational-leasing',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersNewIndividualRoute =
  AuthenticatedOffersNewIndividualRouteImport.update({
    id: '/offers/new/individual',
    path: '/offers/new/individual',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersNewDirectPurchaseRoute =
  AuthenticatedOffersNewDirectPurchaseRouteImport.update({
    id: '/offers/new/direct-purchase',
    path: '/offers/new/direct-purchase',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOffersOfferIdEditRoute =
  AuthenticatedOffersOfferIdEditRouteImport.update({
    id: '/offers/$offerId/edit',
    path: '/offers/$offerId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedModelsModelIdEditRoute =
  AuthenticatedModelsModelIdEditRouteImport.update({
    id: '/models/$modelId/edit',
    path: '/models/$modelId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLeasingCompaniesCompanyIdEditRoute =
  AuthenticatedLeasingCompaniesCompanyIdEditRouteImport.update({
    id: '/leasing-companies/$companyId/edit',
    path: '/leasing-companies/$companyId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerationsGenerationIdEquipmentRoute =
  AuthenticatedGenerationsGenerationIdEquipmentRouteImport.update({
    id: '/generations/$generationId/equipment',
    path: '/generations/$generationId/equipment',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedGenerationsGenerationIdEditRoute =
  AuthenticatedGenerationsGenerationIdEditRouteImport.update({
    id: '/generations/$generationId/edit',
    path: '/generations/$generationId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEquipmentItemsItemIdEditRoute =
  AuthenticatedEquipmentItemsItemIdEditRouteImport.update({
    id: '/equipment-items/$itemId/edit',
    path: '/equipment-items/$itemId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEnginesEngineIdEditRoute =
  AuthenticatedEnginesEngineIdEditRouteImport.update({
    id: '/engines/$engineId/edit',
    path: '/engines/$engineId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDocumentTemplatesTemplateIdEditRoute =
  AuthenticatedDocumentTemplatesTemplateIdEditRouteImport.update({
    id: '/document-templates/$templateId/edit',
    path: '/document-templates/$templateId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedColorsColorIdEditRoute =
  AuthenticatedColorsColorIdEditRouteImport.update({
    id: '/colors/$colorId/edit',
    path: '/colors/$colorId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarRequestsCarRequestIdEditRoute =
  AuthenticatedCarRequestsCarRequestIdEditRouteImport.update({
    id: '/car-requests/$carRequestId/edit',
    path: '/car-requests/$carRequestId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBrandsBrandIdEditRoute =
  AuthenticatedBrandsBrandIdEditRouteImport.update({
    id: '/brands/$brandId/edit',
    path: '/brands/$brandId/edit',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/brands/new': typeof AuthenticatedBrandsNewRoute
  '/car-requests/new': typeof AuthenticatedCarRequestsNewRoute
  '/colors/new': typeof AuthenticatedColorsNewRoute
  '/document-templates/new': typeof AuthenticatedDocumentTemplatesNewRoute
  '/engines/new': typeof AuthenticatedEnginesNewRoute
  '/equipment-items/new': typeof AuthenticatedEquipmentItemsNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/generations/new': typeof AuthenticatedGenerationsNewRoute
  '/leasing-companies/new': typeof AuthenticatedLeasingCompaniesNewRoute
  '/models/new': typeof AuthenticatedModelsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/add': typeof AuthenticatedUsersAddRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/brands': typeof AuthenticatedBrandsIndexRoute
  '/car-requests': typeof AuthenticatedCarRequestsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/colors': typeof AuthenticatedColorsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/discounts': typeof AuthenticatedDiscountsIndexRoute
  '/document-templates': typeof AuthenticatedDocumentTemplatesIndexRoute
  '/engines': typeof AuthenticatedEnginesIndexRoute
  '/equipment-items': typeof AuthenticatedEquipmentItemsIndexRoute
  '/generations': typeof AuthenticatedGenerationsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/leasing-companies': typeof AuthenticatedLeasingCompaniesIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/offers': typeof AuthenticatedOffersIndexRoute
  '/onboardings': typeof AuthenticatedOnboardingsIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/brands/$brandId/edit': typeof AuthenticatedBrandsBrandIdEditRoute
  '/car-requests/$carRequestId/edit': typeof AuthenticatedCarRequestsCarRequestIdEditRoute
  '/colors/$colorId/edit': typeof AuthenticatedColorsColorIdEditRoute
  '/document-templates/$templateId/edit': typeof AuthenticatedDocumentTemplatesTemplateIdEditRoute
  '/engines/$engineId/edit': typeof AuthenticatedEnginesEngineIdEditRoute
  '/equipment-items/$itemId/edit': typeof AuthenticatedEquipmentItemsItemIdEditRoute
  '/generations/$generationId/edit': typeof AuthenticatedGenerationsGenerationIdEditRoute
  '/generations/$generationId/equipment': typeof AuthenticatedGenerationsGenerationIdEquipmentRoute
  '/leasing-companies/$companyId/edit': typeof AuthenticatedLeasingCompaniesCompanyIdEditRoute
  '/models/$modelId/edit': typeof AuthenticatedModelsModelIdEditRoute
  '/offers/$offerId/edit': typeof AuthenticatedOffersOfferIdEditRoute
  '/offers/new/direct-purchase': typeof AuthenticatedOffersNewDirectPurchaseRoute
  '/offers/new/individual': typeof AuthenticatedOffersNewIndividualRoute
  '/offers/new/operational-leasing': typeof AuthenticatedOffersNewOperationalLeasingRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/car-requests/$carRequestId': typeof AuthenticatedCarRequestsCarRequestIdIndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/generations/$generationId': typeof AuthenticatedGenerationsGenerationIdIndexRoute
  '/offers/new': typeof AuthenticatedOffersNewIndexRoute
  '/onboardings/$onboardingId': typeof AuthenticatedOnboardingsOnboardingIdIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof authForgotPasswordRoute
  '/otp': typeof authOtpRoute
  '/sign-in': typeof authSignInRoute
  '/sign-in-2': typeof authSignIn2Route
  '/sign-up': typeof authSignUpRoute
  '/401': typeof errors401Route
  '/403': typeof errors403Route
  '/404': typeof errors404Route
  '/500': typeof errors500Route
  '/503': typeof errors503Route
  '/': typeof AuthenticatedIndexRoute
  '/brands/new': typeof AuthenticatedBrandsNewRoute
  '/car-requests/new': typeof AuthenticatedCarRequestsNewRoute
  '/colors/new': typeof AuthenticatedColorsNewRoute
  '/document-templates/new': typeof AuthenticatedDocumentTemplatesNewRoute
  '/engines/new': typeof AuthenticatedEnginesNewRoute
  '/equipment-items/new': typeof AuthenticatedEquipmentItemsNewRoute
  '/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/generations/new': typeof AuthenticatedGenerationsNewRoute
  '/leasing-companies/new': typeof AuthenticatedLeasingCompaniesNewRoute
  '/models/new': typeof AuthenticatedModelsNewRoute
  '/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/users/add': typeof AuthenticatedUsersAddRoute
  '/apps': typeof AuthenticatedAppsIndexRoute
  '/brands': typeof AuthenticatedBrandsIndexRoute
  '/car-requests': typeof AuthenticatedCarRequestsIndexRoute
  '/chats': typeof AuthenticatedChatsIndexRoute
  '/colors': typeof AuthenticatedColorsIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/discounts': typeof AuthenticatedDiscountsIndexRoute
  '/document-templates': typeof AuthenticatedDocumentTemplatesIndexRoute
  '/engines': typeof AuthenticatedEnginesIndexRoute
  '/equipment-items': typeof AuthenticatedEquipmentItemsIndexRoute
  '/generations': typeof AuthenticatedGenerationsIndexRoute
  '/help-center': typeof AuthenticatedHelpCenterIndexRoute
  '/leasing-companies': typeof AuthenticatedLeasingCompaniesIndexRoute
  '/models': typeof AuthenticatedModelsIndexRoute
  '/offers': typeof AuthenticatedOffersIndexRoute
  '/onboardings': typeof AuthenticatedOnboardingsIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/tasks': typeof AuthenticatedTasksIndexRoute
  '/users': typeof AuthenticatedUsersIndexRoute
  '/brands/$brandId/edit': typeof AuthenticatedBrandsBrandIdEditRoute
  '/car-requests/$carRequestId/edit': typeof AuthenticatedCarRequestsCarRequestIdEditRoute
  '/colors/$colorId/edit': typeof AuthenticatedColorsColorIdEditRoute
  '/document-templates/$templateId/edit': typeof AuthenticatedDocumentTemplatesTemplateIdEditRoute
  '/engines/$engineId/edit': typeof AuthenticatedEnginesEngineIdEditRoute
  '/equipment-items/$itemId/edit': typeof AuthenticatedEquipmentItemsItemIdEditRoute
  '/generations/$generationId/edit': typeof AuthenticatedGenerationsGenerationIdEditRoute
  '/generations/$generationId/equipment': typeof AuthenticatedGenerationsGenerationIdEquipmentRoute
  '/leasing-companies/$companyId/edit': typeof AuthenticatedLeasingCompaniesCompanyIdEditRoute
  '/models/$modelId/edit': typeof AuthenticatedModelsModelIdEditRoute
  '/offers/$offerId/edit': typeof AuthenticatedOffersOfferIdEditRoute
  '/offers/new/direct-purchase': typeof AuthenticatedOffersNewDirectPurchaseRoute
  '/offers/new/individual': typeof AuthenticatedOffersNewIndividualRoute
  '/offers/new/operational-leasing': typeof AuthenticatedOffersNewOperationalLeasingRoute
  '/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/car-requests/$carRequestId': typeof AuthenticatedCarRequestsCarRequestIdIndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/generations/$generationId': typeof AuthenticatedGenerationsGenerationIdIndexRoute
  '/offers/new': typeof AuthenticatedOffersNewIndexRoute
  '/onboardings/$onboardingId': typeof AuthenticatedOnboardingsOnboardingIdIndexRoute
  '/users/$userId': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRouteRouteWithChildren
  '/(auth)/forgot-password': typeof authForgotPasswordRoute
  '/(auth)/otp': typeof authOtpRoute
  '/(auth)/sign-in': typeof authSignInRoute
  '/(auth)/sign-in-2': typeof authSignIn2Route
  '/(auth)/sign-up': typeof authSignUpRoute
  '/(errors)/401': typeof errors401Route
  '/(errors)/403': typeof errors403Route
  '/(errors)/404': typeof errors404Route
  '/(errors)/500': typeof errors500Route
  '/(errors)/503': typeof errors503Route
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/brands/new': typeof AuthenticatedBrandsNewRoute
  '/_authenticated/car-requests/new': typeof AuthenticatedCarRequestsNewRoute
  '/_authenticated/colors/new': typeof AuthenticatedColorsNewRoute
  '/_authenticated/document-templates/new': typeof AuthenticatedDocumentTemplatesNewRoute
  '/_authenticated/engines/new': typeof AuthenticatedEnginesNewRoute
  '/_authenticated/equipment-items/new': typeof AuthenticatedEquipmentItemsNewRoute
  '/_authenticated/errors/$error': typeof AuthenticatedErrorsErrorRoute
  '/_authenticated/generations/new': typeof AuthenticatedGenerationsNewRoute
  '/_authenticated/leasing-companies/new': typeof AuthenticatedLeasingCompaniesNewRoute
  '/_authenticated/models/new': typeof AuthenticatedModelsNewRoute
  '/_authenticated/settings/account': typeof AuthenticatedSettingsAccountRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/settings/display': typeof AuthenticatedSettingsDisplayRoute
  '/_authenticated/settings/notifications': typeof AuthenticatedSettingsNotificationsRoute
  '/_authenticated/users/add': typeof AuthenticatedUsersAddRoute
  '/_authenticated/apps/': typeof AuthenticatedAppsIndexRoute
  '/_authenticated/brands/': typeof AuthenticatedBrandsIndexRoute
  '/_authenticated/car-requests/': typeof AuthenticatedCarRequestsIndexRoute
  '/_authenticated/chats/': typeof AuthenticatedChatsIndexRoute
  '/_authenticated/colors/': typeof AuthenticatedColorsIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/discounts/': typeof AuthenticatedDiscountsIndexRoute
  '/_authenticated/document-templates/': typeof AuthenticatedDocumentTemplatesIndexRoute
  '/_authenticated/engines/': typeof AuthenticatedEnginesIndexRoute
  '/_authenticated/equipment-items/': typeof AuthenticatedEquipmentItemsIndexRoute
  '/_authenticated/generations/': typeof AuthenticatedGenerationsIndexRoute
  '/_authenticated/help-center/': typeof AuthenticatedHelpCenterIndexRoute
  '/_authenticated/leasing-companies/': typeof AuthenticatedLeasingCompaniesIndexRoute
  '/_authenticated/models/': typeof AuthenticatedModelsIndexRoute
  '/_authenticated/offers/': typeof AuthenticatedOffersIndexRoute
  '/_authenticated/onboardings/': typeof AuthenticatedOnboardingsIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/tasks/': typeof AuthenticatedTasksIndexRoute
  '/_authenticated/users/': typeof AuthenticatedUsersIndexRoute
  '/_authenticated/brands/$brandId/edit': typeof AuthenticatedBrandsBrandIdEditRoute
  '/_authenticated/car-requests/$carRequestId/edit': typeof AuthenticatedCarRequestsCarRequestIdEditRoute
  '/_authenticated/colors/$colorId/edit': typeof AuthenticatedColorsColorIdEditRoute
  '/_authenticated/document-templates/$templateId/edit': typeof AuthenticatedDocumentTemplatesTemplateIdEditRoute
  '/_authenticated/engines/$engineId/edit': typeof AuthenticatedEnginesEngineIdEditRoute
  '/_authenticated/equipment-items/$itemId/edit': typeof AuthenticatedEquipmentItemsItemIdEditRoute
  '/_authenticated/generations/$generationId/edit': typeof AuthenticatedGenerationsGenerationIdEditRoute
  '/_authenticated/generations/$generationId/equipment': typeof AuthenticatedGenerationsGenerationIdEquipmentRoute
  '/_authenticated/leasing-companies/$companyId/edit': typeof AuthenticatedLeasingCompaniesCompanyIdEditRoute
  '/_authenticated/models/$modelId/edit': typeof AuthenticatedModelsModelIdEditRoute
  '/_authenticated/offers/$offerId/edit': typeof AuthenticatedOffersOfferIdEditRoute
  '/_authenticated/offers/new/direct-purchase': typeof AuthenticatedOffersNewDirectPurchaseRoute
  '/_authenticated/offers/new/individual': typeof AuthenticatedOffersNewIndividualRoute
  '/_authenticated/offers/new/operational-leasing': typeof AuthenticatedOffersNewOperationalLeasingRoute
  '/_authenticated/users/$userId/edit': typeof AuthenticatedUsersUserIdEditRoute
  '/_authenticated/car-requests/$carRequestId/': typeof AuthenticatedCarRequestsCarRequestIdIndexRoute
  '/_authenticated/customers/$customerId/': typeof AuthenticatedCustomersCustomerIdIndexRoute
  '/_authenticated/generations/$generationId/': typeof AuthenticatedGenerationsGenerationIdIndexRoute
  '/_authenticated/offers/new/': typeof AuthenticatedOffersNewIndexRoute
  '/_authenticated/onboardings/$onboardingId/': typeof AuthenticatedOnboardingsOnboardingIdIndexRoute
  '/_authenticated/users/$userId/': typeof AuthenticatedUsersUserIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/brands/new'
    | '/car-requests/new'
    | '/colors/new'
    | '/document-templates/new'
    | '/engines/new'
    | '/equipment-items/new'
    | '/errors/$error'
    | '/generations/new'
    | '/leasing-companies/new'
    | '/models/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/add'
    | '/apps'
    | '/brands'
    | '/car-requests'
    | '/chats'
    | '/colors'
    | '/customers'
    | '/discounts'
    | '/document-templates'
    | '/engines'
    | '/equipment-items'
    | '/generations'
    | '/help-center'
    | '/leasing-companies'
    | '/models'
    | '/offers'
    | '/onboardings'
    | '/settings/'
    | '/tasks'
    | '/users'
    | '/brands/$brandId/edit'
    | '/car-requests/$carRequestId/edit'
    | '/colors/$colorId/edit'
    | '/document-templates/$templateId/edit'
    | '/engines/$engineId/edit'
    | '/equipment-items/$itemId/edit'
    | '/generations/$generationId/edit'
    | '/generations/$generationId/equipment'
    | '/leasing-companies/$companyId/edit'
    | '/models/$modelId/edit'
    | '/offers/$offerId/edit'
    | '/offers/new/direct-purchase'
    | '/offers/new/individual'
    | '/offers/new/operational-leasing'
    | '/users/$userId/edit'
    | '/car-requests/$carRequestId'
    | '/customers/$customerId'
    | '/generations/$generationId'
    | '/offers/new'
    | '/onboardings/$onboardingId'
    | '/users/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/otp'
    | '/sign-in'
    | '/sign-in-2'
    | '/sign-up'
    | '/401'
    | '/403'
    | '/404'
    | '/500'
    | '/503'
    | '/'
    | '/brands/new'
    | '/car-requests/new'
    | '/colors/new'
    | '/document-templates/new'
    | '/engines/new'
    | '/equipment-items/new'
    | '/errors/$error'
    | '/generations/new'
    | '/leasing-companies/new'
    | '/models/new'
    | '/settings/account'
    | '/settings/appearance'
    | '/settings/display'
    | '/settings/notifications'
    | '/users/add'
    | '/apps'
    | '/brands'
    | '/car-requests'
    | '/chats'
    | '/colors'
    | '/customers'
    | '/discounts'
    | '/document-templates'
    | '/engines'
    | '/equipment-items'
    | '/generations'
    | '/help-center'
    | '/leasing-companies'
    | '/models'
    | '/offers'
    | '/onboardings'
    | '/settings'
    | '/tasks'
    | '/users'
    | '/brands/$brandId/edit'
    | '/car-requests/$carRequestId/edit'
    | '/colors/$colorId/edit'
    | '/document-templates/$templateId/edit'
    | '/engines/$engineId/edit'
    | '/equipment-items/$itemId/edit'
    | '/generations/$generationId/edit'
    | '/generations/$generationId/equipment'
    | '/leasing-companies/$companyId/edit'
    | '/models/$modelId/edit'
    | '/offers/$offerId/edit'
    | '/offers/new/direct-purchase'
    | '/offers/new/individual'
    | '/offers/new/operational-leasing'
    | '/users/$userId/edit'
    | '/car-requests/$carRequestId'
    | '/customers/$customerId'
    | '/generations/$generationId'
    | '/offers/new'
    | '/onboardings/$onboardingId'
    | '/users/$userId'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_authenticated/settings'
    | '/(auth)/forgot-password'
    | '/(auth)/otp'
    | '/(auth)/sign-in'
    | '/(auth)/sign-in-2'
    | '/(auth)/sign-up'
    | '/(errors)/401'
    | '/(errors)/403'
    | '/(errors)/404'
    | '/(errors)/500'
    | '/(errors)/503'
    | '/_authenticated/'
    | '/_authenticated/brands/new'
    | '/_authenticated/car-requests/new'
    | '/_authenticated/colors/new'
    | '/_authenticated/document-templates/new'
    | '/_authenticated/engines/new'
    | '/_authenticated/equipment-items/new'
    | '/_authenticated/errors/$error'
    | '/_authenticated/generations/new'
    | '/_authenticated/leasing-companies/new'
    | '/_authenticated/models/new'
    | '/_authenticated/settings/account'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/settings/display'
    | '/_authenticated/settings/notifications'
    | '/_authenticated/users/add'
    | '/_authenticated/apps/'
    | '/_authenticated/brands/'
    | '/_authenticated/car-requests/'
    | '/_authenticated/chats/'
    | '/_authenticated/colors/'
    | '/_authenticated/customers/'
    | '/_authenticated/discounts/'
    | '/_authenticated/document-templates/'
    | '/_authenticated/engines/'
    | '/_authenticated/equipment-items/'
    | '/_authenticated/generations/'
    | '/_authenticated/help-center/'
    | '/_authenticated/leasing-companies/'
    | '/_authenticated/models/'
    | '/_authenticated/offers/'
    | '/_authenticated/onboardings/'
    | '/_authenticated/settings/'
    | '/_authenticated/tasks/'
    | '/_authenticated/users/'
    | '/_authenticated/brands/$brandId/edit'
    | '/_authenticated/car-requests/$carRequestId/edit'
    | '/_authenticated/colors/$colorId/edit'
    | '/_authenticated/document-templates/$templateId/edit'
    | '/_authenticated/engines/$engineId/edit'
    | '/_authenticated/equipment-items/$itemId/edit'
    | '/_authenticated/generations/$generationId/edit'
    | '/_authenticated/generations/$generationId/equipment'
    | '/_authenticated/leasing-companies/$companyId/edit'
    | '/_authenticated/models/$modelId/edit'
    | '/_authenticated/offers/$offerId/edit'
    | '/_authenticated/offers/new/direct-purchase'
    | '/_authenticated/offers/new/individual'
    | '/_authenticated/offers/new/operational-leasing'
    | '/_authenticated/users/$userId/edit'
    | '/_authenticated/car-requests/$carRequestId/'
    | '/_authenticated/customers/$customerId/'
    | '/_authenticated/generations/$generationId/'
    | '/_authenticated/offers/new/'
    | '/_authenticated/onboardings/$onboardingId/'
    | '/_authenticated/users/$userId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authForgotPasswordRoute: typeof authForgotPasswordRoute
  authOtpRoute: typeof authOtpRoute
  authSignInRoute: typeof authSignInRoute
  authSignIn2Route: typeof authSignIn2Route
  authSignUpRoute: typeof authSignUpRoute
  errors401Route: typeof errors401Route
  errors403Route: typeof errors403Route
  errors404Route: typeof errors404Route
  errors500Route: typeof errors500Route
  errors503Route: typeof errors503Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(errors)/503': {
      id: '/(errors)/503'
      path: '/503'
      fullPath: '/503'
      preLoaderRoute: typeof errors503RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/500': {
      id: '/(errors)/500'
      path: '/500'
      fullPath: '/500'
      preLoaderRoute: typeof errors500RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/404': {
      id: '/(errors)/404'
      path: '/404'
      fullPath: '/404'
      preLoaderRoute: typeof errors404RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/403': {
      id: '/(errors)/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof errors403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(errors)/401': {
      id: '/(errors)/401'
      path: '/401'
      fullPath: '/401'
      preLoaderRoute: typeof errors401RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-up': {
      id: '/(auth)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof authSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in-2': {
      id: '/(auth)/sign-in-2'
      path: '/sign-in-2'
      fullPath: '/sign-in-2'
      preLoaderRoute: typeof authSignIn2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/sign-in': {
      id: '/(auth)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof authSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/otp': {
      id: '/(auth)/otp'
      path: '/otp'
      fullPath: '/otp'
      preLoaderRoute: typeof authOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(auth)/forgot-password': {
      id: '/(auth)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/': {
      id: '/_authenticated/users/'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks/': {
      id: '/_authenticated/tasks/'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/onboardings/': {
      id: '/_authenticated/onboardings/'
      path: '/onboardings'
      fullPath: '/onboardings'
      preLoaderRoute: typeof AuthenticatedOnboardingsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/': {
      id: '/_authenticated/offers/'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof AuthenticatedOffersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/': {
      id: '/_authenticated/models/'
      path: '/models'
      fullPath: '/models'
      preLoaderRoute: typeof AuthenticatedModelsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leasing-companies/': {
      id: '/_authenticated/leasing-companies/'
      path: '/leasing-companies'
      fullPath: '/leasing-companies'
      preLoaderRoute: typeof AuthenticatedLeasingCompaniesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/help-center/': {
      id: '/_authenticated/help-center/'
      path: '/help-center'
      fullPath: '/help-center'
      preLoaderRoute: typeof AuthenticatedHelpCenterIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generations/': {
      id: '/_authenticated/generations/'
      path: '/generations'
      fullPath: '/generations'
      preLoaderRoute: typeof AuthenticatedGenerationsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment-items/': {
      id: '/_authenticated/equipment-items/'
      path: '/equipment-items'
      fullPath: '/equipment-items'
      preLoaderRoute: typeof AuthenticatedEquipmentItemsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engines/': {
      id: '/_authenticated/engines/'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof AuthenticatedEnginesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document-templates/': {
      id: '/_authenticated/document-templates/'
      path: '/document-templates'
      fullPath: '/document-templates'
      preLoaderRoute: typeof AuthenticatedDocumentTemplatesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/discounts/': {
      id: '/_authenticated/discounts/'
      path: '/discounts'
      fullPath: '/discounts'
      preLoaderRoute: typeof AuthenticatedDiscountsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colors/': {
      id: '/_authenticated/colors/'
      path: '/colors'
      fullPath: '/colors'
      preLoaderRoute: typeof AuthenticatedColorsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats/': {
      id: '/_authenticated/chats/'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/car-requests/': {
      id: '/_authenticated/car-requests/'
      path: '/car-requests'
      fullPath: '/car-requests'
      preLoaderRoute: typeof AuthenticatedCarRequestsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/': {
      id: '/_authenticated/brands/'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AuthenticatedBrandsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/apps/': {
      id: '/_authenticated/apps/'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AuthenticatedAppsIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/add': {
      id: '/_authenticated/users/add'
      path: '/users/add'
      fullPath: '/users/add'
      preLoaderRoute: typeof AuthenticatedUsersAddRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings/notifications': {
      id: '/_authenticated/settings/notifications'
      path: '/notifications'
      fullPath: '/settings/notifications'
      preLoaderRoute: typeof AuthenticatedSettingsNotificationsRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/display': {
      id: '/_authenticated/settings/display'
      path: '/display'
      fullPath: '/settings/display'
      preLoaderRoute: typeof AuthenticatedSettingsDisplayRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/settings/account': {
      id: '/_authenticated/settings/account'
      path: '/account'
      fullPath: '/settings/account'
      preLoaderRoute: typeof AuthenticatedSettingsAccountRouteImport
      parentRoute: typeof AuthenticatedSettingsRouteRoute
    }
    '/_authenticated/models/new': {
      id: '/_authenticated/models/new'
      path: '/models/new'
      fullPath: '/models/new'
      preLoaderRoute: typeof AuthenticatedModelsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leasing-companies/new': {
      id: '/_authenticated/leasing-companies/new'
      path: '/leasing-companies/new'
      fullPath: '/leasing-companies/new'
      preLoaderRoute: typeof AuthenticatedLeasingCompaniesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generations/new': {
      id: '/_authenticated/generations/new'
      path: '/generations/new'
      fullPath: '/generations/new'
      preLoaderRoute: typeof AuthenticatedGenerationsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/errors/$error': {
      id: '/_authenticated/errors/$error'
      path: '/errors/$error'
      fullPath: '/errors/$error'
      preLoaderRoute: typeof AuthenticatedErrorsErrorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment-items/new': {
      id: '/_authenticated/equipment-items/new'
      path: '/equipment-items/new'
      fullPath: '/equipment-items/new'
      preLoaderRoute: typeof AuthenticatedEquipmentItemsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engines/new': {
      id: '/_authenticated/engines/new'
      path: '/engines/new'
      fullPath: '/engines/new'
      preLoaderRoute: typeof AuthenticatedEnginesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document-templates/new': {
      id: '/_authenticated/document-templates/new'
      path: '/document-templates/new'
      fullPath: '/document-templates/new'
      preLoaderRoute: typeof AuthenticatedDocumentTemplatesNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colors/new': {
      id: '/_authenticated/colors/new'
      path: '/colors/new'
      fullPath: '/colors/new'
      preLoaderRoute: typeof AuthenticatedColorsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/car-requests/new': {
      id: '/_authenticated/car-requests/new'
      path: '/car-requests/new'
      fullPath: '/car-requests/new'
      preLoaderRoute: typeof AuthenticatedCarRequestsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/new': {
      id: '/_authenticated/brands/new'
      path: '/brands/new'
      fullPath: '/brands/new'
      preLoaderRoute: typeof AuthenticatedBrandsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$userId/': {
      id: '/_authenticated/users/$userId/'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AuthenticatedUsersUserIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboardings/$onboardingId/': {
      id: '/_authenticated/onboardings/$onboardingId/'
      path: '/onboardings/$onboardingId'
      fullPath: '/onboardings/$onboardingId'
      preLoaderRoute: typeof AuthenticatedOnboardingsOnboardingIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/new/': {
      id: '/_authenticated/offers/new/'
      path: '/offers/new'
      fullPath: '/offers/new'
      preLoaderRoute: typeof AuthenticatedOffersNewIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generations/$generationId/': {
      id: '/_authenticated/generations/$generationId/'
      path: '/generations/$generationId'
      fullPath: '/generations/$generationId'
      preLoaderRoute: typeof AuthenticatedGenerationsGenerationIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/customers/$customerId/': {
      id: '/_authenticated/customers/$customerId/'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/car-requests/$carRequestId/': {
      id: '/_authenticated/car-requests/$carRequestId/'
      path: '/car-requests/$carRequestId'
      fullPath: '/car-requests/$carRequestId'
      preLoaderRoute: typeof AuthenticatedCarRequestsCarRequestIdIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/users/$userId/edit': {
      id: '/_authenticated/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/users/$userId/edit'
      preLoaderRoute: typeof AuthenticatedUsersUserIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/new/operational-leasing': {
      id: '/_authenticated/offers/new/operational-leasing'
      path: '/offers/new/operational-leasing'
      fullPath: '/offers/new/operational-leasing'
      preLoaderRoute: typeof AuthenticatedOffersNewOperationalLeasingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/new/individual': {
      id: '/_authenticated/offers/new/individual'
      path: '/offers/new/individual'
      fullPath: '/offers/new/individual'
      preLoaderRoute: typeof AuthenticatedOffersNewIndividualRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/new/direct-purchase': {
      id: '/_authenticated/offers/new/direct-purchase'
      path: '/offers/new/direct-purchase'
      fullPath: '/offers/new/direct-purchase'
      preLoaderRoute: typeof AuthenticatedOffersNewDirectPurchaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/offers/$offerId/edit': {
      id: '/_authenticated/offers/$offerId/edit'
      path: '/offers/$offerId/edit'
      fullPath: '/offers/$offerId/edit'
      preLoaderRoute: typeof AuthenticatedOffersOfferIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/models/$modelId/edit': {
      id: '/_authenticated/models/$modelId/edit'
      path: '/models/$modelId/edit'
      fullPath: '/models/$modelId/edit'
      preLoaderRoute: typeof AuthenticatedModelsModelIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/leasing-companies/$companyId/edit': {
      id: '/_authenticated/leasing-companies/$companyId/edit'
      path: '/leasing-companies/$companyId/edit'
      fullPath: '/leasing-companies/$companyId/edit'
      preLoaderRoute: typeof AuthenticatedLeasingCompaniesCompanyIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generations/$generationId/equipment': {
      id: '/_authenticated/generations/$generationId/equipment'
      path: '/generations/$generationId/equipment'
      fullPath: '/generations/$generationId/equipment'
      preLoaderRoute: typeof AuthenticatedGenerationsGenerationIdEquipmentRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/generations/$generationId/edit': {
      id: '/_authenticated/generations/$generationId/edit'
      path: '/generations/$generationId/edit'
      fullPath: '/generations/$generationId/edit'
      preLoaderRoute: typeof AuthenticatedGenerationsGenerationIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/equipment-items/$itemId/edit': {
      id: '/_authenticated/equipment-items/$itemId/edit'
      path: '/equipment-items/$itemId/edit'
      fullPath: '/equipment-items/$itemId/edit'
      preLoaderRoute: typeof AuthenticatedEquipmentItemsItemIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/engines/$engineId/edit': {
      id: '/_authenticated/engines/$engineId/edit'
      path: '/engines/$engineId/edit'
      fullPath: '/engines/$engineId/edit'
      preLoaderRoute: typeof AuthenticatedEnginesEngineIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/document-templates/$templateId/edit': {
      id: '/_authenticated/document-templates/$templateId/edit'
      path: '/document-templates/$templateId/edit'
      fullPath: '/document-templates/$templateId/edit'
      preLoaderRoute: typeof AuthenticatedDocumentTemplatesTemplateIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/colors/$colorId/edit': {
      id: '/_authenticated/colors/$colorId/edit'
      path: '/colors/$colorId/edit'
      fullPath: '/colors/$colorId/edit'
      preLoaderRoute: typeof AuthenticatedColorsColorIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/car-requests/$carRequestId/edit': {
      id: '/_authenticated/car-requests/$carRequestId/edit'
      path: '/car-requests/$carRequestId/edit'
      fullPath: '/car-requests/$carRequestId/edit'
      preLoaderRoute: typeof AuthenticatedCarRequestsCarRequestIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brands/$brandId/edit': {
      id: '/_authenticated/brands/$brandId/edit'
      path: '/brands/$brandId/edit'
      fullPath: '/brands/$brandId/edit'
      preLoaderRoute: typeof AuthenticatedBrandsBrandIdEditRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedSettingsRouteRouteChildren {
  AuthenticatedSettingsAccountRoute: typeof AuthenticatedSettingsAccountRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
  AuthenticatedSettingsDisplayRoute: typeof AuthenticatedSettingsDisplayRoute
  AuthenticatedSettingsNotificationsRoute: typeof AuthenticatedSettingsNotificationsRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
}

const AuthenticatedSettingsRouteRouteChildren: AuthenticatedSettingsRouteRouteChildren =
  {
    AuthenticatedSettingsAccountRoute: AuthenticatedSettingsAccountRoute,
    AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
    AuthenticatedSettingsDisplayRoute: AuthenticatedSettingsDisplayRoute,
    AuthenticatedSettingsNotificationsRoute:
      AuthenticatedSettingsNotificationsRoute,
    AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  }

const AuthenticatedSettingsRouteRouteWithChildren =
  AuthenticatedSettingsRouteRoute._addFileChildren(
    AuthenticatedSettingsRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedSettingsRouteRoute: typeof AuthenticatedSettingsRouteRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedBrandsNewRoute: typeof AuthenticatedBrandsNewRoute
  AuthenticatedCarRequestsNewRoute: typeof AuthenticatedCarRequestsNewRoute
  AuthenticatedColorsNewRoute: typeof AuthenticatedColorsNewRoute
  AuthenticatedDocumentTemplatesNewRoute: typeof AuthenticatedDocumentTemplatesNewRoute
  AuthenticatedEnginesNewRoute: typeof AuthenticatedEnginesNewRoute
  AuthenticatedEquipmentItemsNewRoute: typeof AuthenticatedEquipmentItemsNewRoute
  AuthenticatedErrorsErrorRoute: typeof AuthenticatedErrorsErrorRoute
  AuthenticatedGenerationsNewRoute: typeof AuthenticatedGenerationsNewRoute
  AuthenticatedLeasingCompaniesNewRoute: typeof AuthenticatedLeasingCompaniesNewRoute
  AuthenticatedModelsNewRoute: typeof AuthenticatedModelsNewRoute
  AuthenticatedUsersAddRoute: typeof AuthenticatedUsersAddRoute
  AuthenticatedAppsIndexRoute: typeof AuthenticatedAppsIndexRoute
  AuthenticatedBrandsIndexRoute: typeof AuthenticatedBrandsIndexRoute
  AuthenticatedCarRequestsIndexRoute: typeof AuthenticatedCarRequestsIndexRoute
  AuthenticatedChatsIndexRoute: typeof AuthenticatedChatsIndexRoute
  AuthenticatedColorsIndexRoute: typeof AuthenticatedColorsIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedDiscountsIndexRoute: typeof AuthenticatedDiscountsIndexRoute
  AuthenticatedDocumentTemplatesIndexRoute: typeof AuthenticatedDocumentTemplatesIndexRoute
  AuthenticatedEnginesIndexRoute: typeof AuthenticatedEnginesIndexRoute
  AuthenticatedEquipmentItemsIndexRoute: typeof AuthenticatedEquipmentItemsIndexRoute
  AuthenticatedGenerationsIndexRoute: typeof AuthenticatedGenerationsIndexRoute
  AuthenticatedHelpCenterIndexRoute: typeof AuthenticatedHelpCenterIndexRoute
  AuthenticatedLeasingCompaniesIndexRoute: typeof AuthenticatedLeasingCompaniesIndexRoute
  AuthenticatedModelsIndexRoute: typeof AuthenticatedModelsIndexRoute
  AuthenticatedOffersIndexRoute: typeof AuthenticatedOffersIndexRoute
  AuthenticatedOnboardingsIndexRoute: typeof AuthenticatedOnboardingsIndexRoute
  AuthenticatedTasksIndexRoute: typeof AuthenticatedTasksIndexRoute
  AuthenticatedUsersIndexRoute: typeof AuthenticatedUsersIndexRoute
  AuthenticatedBrandsBrandIdEditRoute: typeof AuthenticatedBrandsBrandIdEditRoute
  AuthenticatedCarRequestsCarRequestIdEditRoute: typeof AuthenticatedCarRequestsCarRequestIdEditRoute
  AuthenticatedColorsColorIdEditRoute: typeof AuthenticatedColorsColorIdEditRoute
  AuthenticatedDocumentTemplatesTemplateIdEditRoute: typeof AuthenticatedDocumentTemplatesTemplateIdEditRoute
  AuthenticatedEnginesEngineIdEditRoute: typeof AuthenticatedEnginesEngineIdEditRoute
  AuthenticatedEquipmentItemsItemIdEditRoute: typeof AuthenticatedEquipmentItemsItemIdEditRoute
  AuthenticatedGenerationsGenerationIdEditRoute: typeof AuthenticatedGenerationsGenerationIdEditRoute
  AuthenticatedGenerationsGenerationIdEquipmentRoute: typeof AuthenticatedGenerationsGenerationIdEquipmentRoute
  AuthenticatedLeasingCompaniesCompanyIdEditRoute: typeof AuthenticatedLeasingCompaniesCompanyIdEditRoute
  AuthenticatedModelsModelIdEditRoute: typeof AuthenticatedModelsModelIdEditRoute
  AuthenticatedOffersOfferIdEditRoute: typeof AuthenticatedOffersOfferIdEditRoute
  AuthenticatedOffersNewDirectPurchaseRoute: typeof AuthenticatedOffersNewDirectPurchaseRoute
  AuthenticatedOffersNewIndividualRoute: typeof AuthenticatedOffersNewIndividualRoute
  AuthenticatedOffersNewOperationalLeasingRoute: typeof AuthenticatedOffersNewOperationalLeasingRoute
  AuthenticatedUsersUserIdEditRoute: typeof AuthenticatedUsersUserIdEditRoute
  AuthenticatedCarRequestsCarRequestIdIndexRoute: typeof AuthenticatedCarRequestsCarRequestIdIndexRoute
  AuthenticatedCustomersCustomerIdIndexRoute: typeof AuthenticatedCustomersCustomerIdIndexRoute
  AuthenticatedGenerationsGenerationIdIndexRoute: typeof AuthenticatedGenerationsGenerationIdIndexRoute
  AuthenticatedOffersNewIndexRoute: typeof AuthenticatedOffersNewIndexRoute
  AuthenticatedOnboardingsOnboardingIdIndexRoute: typeof AuthenticatedOnboardingsOnboardingIdIndexRoute
  AuthenticatedUsersUserIdIndexRoute: typeof AuthenticatedUsersUserIdIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedSettingsRouteRoute: AuthenticatedSettingsRouteRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedBrandsNewRoute: AuthenticatedBrandsNewRoute,
  AuthenticatedCarRequestsNewRoute: AuthenticatedCarRequestsNewRoute,
  AuthenticatedColorsNewRoute: AuthenticatedColorsNewRoute,
  AuthenticatedDocumentTemplatesNewRoute:
    AuthenticatedDocumentTemplatesNewRoute,
  AuthenticatedEnginesNewRoute: AuthenticatedEnginesNewRoute,
  AuthenticatedEquipmentItemsNewRoute: AuthenticatedEquipmentItemsNewRoute,
  AuthenticatedErrorsErrorRoute: AuthenticatedErrorsErrorRoute,
  AuthenticatedGenerationsNewRoute: AuthenticatedGenerationsNewRoute,
  AuthenticatedLeasingCompaniesNewRoute: AuthenticatedLeasingCompaniesNewRoute,
  AuthenticatedModelsNewRoute: AuthenticatedModelsNewRoute,
  AuthenticatedUsersAddRoute: AuthenticatedUsersAddRoute,
  AuthenticatedAppsIndexRoute: AuthenticatedAppsIndexRoute,
  AuthenticatedBrandsIndexRoute: AuthenticatedBrandsIndexRoute,
  AuthenticatedCarRequestsIndexRoute: AuthenticatedCarRequestsIndexRoute,
  AuthenticatedChatsIndexRoute: AuthenticatedChatsIndexRoute,
  AuthenticatedColorsIndexRoute: AuthenticatedColorsIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedDiscountsIndexRoute: AuthenticatedDiscountsIndexRoute,
  AuthenticatedDocumentTemplatesIndexRoute:
    AuthenticatedDocumentTemplatesIndexRoute,
  AuthenticatedEnginesIndexRoute: AuthenticatedEnginesIndexRoute,
  AuthenticatedEquipmentItemsIndexRoute: AuthenticatedEquipmentItemsIndexRoute,
  AuthenticatedGenerationsIndexRoute: AuthenticatedGenerationsIndexRoute,
  AuthenticatedHelpCenterIndexRoute: AuthenticatedHelpCenterIndexRoute,
  AuthenticatedLeasingCompaniesIndexRoute:
    AuthenticatedLeasingCompaniesIndexRoute,
  AuthenticatedModelsIndexRoute: AuthenticatedModelsIndexRoute,
  AuthenticatedOffersIndexRoute: AuthenticatedOffersIndexRoute,
  AuthenticatedOnboardingsIndexRoute: AuthenticatedOnboardingsIndexRoute,
  AuthenticatedTasksIndexRoute: AuthenticatedTasksIndexRoute,
  AuthenticatedUsersIndexRoute: AuthenticatedUsersIndexRoute,
  AuthenticatedBrandsBrandIdEditRoute: AuthenticatedBrandsBrandIdEditRoute,
  AuthenticatedCarRequestsCarRequestIdEditRoute:
    AuthenticatedCarRequestsCarRequestIdEditRoute,
  AuthenticatedColorsColorIdEditRoute: AuthenticatedColorsColorIdEditRoute,
  AuthenticatedDocumentTemplatesTemplateIdEditRoute:
    AuthenticatedDocumentTemplatesTemplateIdEditRoute,
  AuthenticatedEnginesEngineIdEditRoute: AuthenticatedEnginesEngineIdEditRoute,
  AuthenticatedEquipmentItemsItemIdEditRoute:
    AuthenticatedEquipmentItemsItemIdEditRoute,
  AuthenticatedGenerationsGenerationIdEditRoute:
    AuthenticatedGenerationsGenerationIdEditRoute,
  AuthenticatedGenerationsGenerationIdEquipmentRoute:
    AuthenticatedGenerationsGenerationIdEquipmentRoute,
  AuthenticatedLeasingCompaniesCompanyIdEditRoute:
    AuthenticatedLeasingCompaniesCompanyIdEditRoute,
  AuthenticatedModelsModelIdEditRoute: AuthenticatedModelsModelIdEditRoute,
  AuthenticatedOffersOfferIdEditRoute: AuthenticatedOffersOfferIdEditRoute,
  AuthenticatedOffersNewDirectPurchaseRoute:
    AuthenticatedOffersNewDirectPurchaseRoute,
  AuthenticatedOffersNewIndividualRoute: AuthenticatedOffersNewIndividualRoute,
  AuthenticatedOffersNewOperationalLeasingRoute:
    AuthenticatedOffersNewOperationalLeasingRoute,
  AuthenticatedUsersUserIdEditRoute: AuthenticatedUsersUserIdEditRoute,
  AuthenticatedCarRequestsCarRequestIdIndexRoute:
    AuthenticatedCarRequestsCarRequestIdIndexRoute,
  AuthenticatedCustomersCustomerIdIndexRoute:
    AuthenticatedCustomersCustomerIdIndexRoute,
  AuthenticatedGenerationsGenerationIdIndexRoute:
    AuthenticatedGenerationsGenerationIdIndexRoute,
  AuthenticatedOffersNewIndexRoute: AuthenticatedOffersNewIndexRoute,
  AuthenticatedOnboardingsOnboardingIdIndexRoute:
    AuthenticatedOnboardingsOnboardingIdIndexRoute,
  AuthenticatedUsersUserIdIndexRoute: AuthenticatedUsersUserIdIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authForgotPasswordRoute: authForgotPasswordRoute,
  authOtpRoute: authOtpRoute,
  authSignInRoute: authSignInRoute,
  authSignIn2Route: authSignIn2Route,
  authSignUpRoute: authSignUpRoute,
  errors401Route: errors401Route,
  errors403Route: errors403Route,
  errors404Route: errors404Route,
  errors500Route: errors500Route,
  errors503Route: errors503Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
