services:
  postgres:
    image: postgres:16-alpine
    container_name: cartop-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USERNAME:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-cartop_v3}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${DB_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME:-postgres} -d ${DB_DATABASE:-cartop_v3}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cartop-network

  # Redis for Bull queues and caching
  redis:
    image: redis:7-alpine
    container_name: cartop-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cartop-network

  adminer:
    container_name: adminer
    image: michalhosna/adminer:latest
    ports:
      - '8080:8080'
    environment:
      ADMINER_DRIVER: pgsql
      ADMINER_SERVER: postgres
      ADMINER_DB: ${DB_DATABASE}
      ADMINER_USERNAME: ${DB_USERNAME}
      ADMINER_PASSWORD: ${DB_PASSWORD}
      ADMINER_AUTOLOGIN: 1
    networks:
      - cartop-network

  minio:
    container_name: minio
    image: bitnami/minio
    environment:
      MINIO_ROOT_USER: 'cartop'
      MINIO_ROOT_PASSWORD: 'cartop1337'
      MINIO_SERVER_URL: 'http://localhost:1483'
      MINIO_BROWSER_REDIRECT_URL: 'http://localhost:1484'
    ports:
      - '1483:9000'
      - '1484:9001'
    volumes:
      - minio-data:/bitnami/minio/data
    entrypoint: >
      bash -c "
        /opt/bitnami/scripts/minio/entrypoint.sh /opt/bitnami/scripts/minio/run.sh &
        sleep 10 &&
        /opt/bitnami/minio-client/bin/mc alias set local http://localhost:9000 cartop cartop1337 &&
        /opt/bitnami/minio-client/bin/mc mb local/pangea || true &&
        /opt/bitnami/minio-client/bin/mc anonymous set download local/pangea &&
        tail -f /dev/null
      "
    networks:
      - cartop-network

  localstack:
    container_name: localstack
    image: localstack/localstack:latest
    ports:
      - 4566:4566
    volumes:
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
    networks:
      - cartop-network

  nginx:
    container_name: nginx
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - adminer
      - minio
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/var/www/html
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/logs:/var/log/nginx
    networks:
      - cartop-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local
  minio-data:

networks:
  cartop-network:
    driver: bridge
